### ISSUE TITLE
部分聊天记录解析异常

### ISSUE THREAD

**Issue by jerrylususu** [kifuan/qq-chat-history#1]
Hi! 首先我很感谢这个项目，给我自己处理数据帮了忙。但是在我使用的过程中发现似乎部分正常的聊天记录，解析的时候会有些异常。具体如下所示：

1. 消息中如果是个纯日期，无法被正确解析

输入
```
2021-11-30 22:30:36 username_hidden(123456789)
go 的这个语法比较特殊，是 month, day, hour, minute, second, year

2021-11-30 22:30:21 username_hidden(123456789)
2006-01-02 15:04:05
```

输出
```
Traceback (most recent call last):
  File "C:\Users\[REMOVED]\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\[REMOVED]\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "[REMOVED]Scripts\qq-chat-history.exe\__main__.py", line 7, in <module>
  File "[REMOVED]lib\site-packages\click\core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "[REMOVED]lib\site-packages\click\core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "[REMOVED]lib\site-packages\click\core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "[REMOVED]lib\site-packages\click\core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "[REMOVED]lib\site-packages\qq_chat_history\cli.py", line 18, in run
    messages = [msg.__dict__ for msg in parser.parse(lines)]
  File "[REMOVED]lib\site-packages\qq_chat_history\cli.py", line 18, in <listcomp>
    messages = [msg.__dict__ for msg in parser.parse(lines)]
  File "[REMOVED]lib\site-packages\qq_chat_history\parser.py", line 63, in parse
    extracted_id = self._extract_id(line)
  File "[REMOVED]lib\site-packages\qq_chat_history\parser.py", line 116, in _extract_id
    raise LookupError(f'cannot find id in line {line}')
LookupError: cannot find id in line 2006-01-02 15:04:05
```

2. 如果昵称包含括号，可能会导致解析结果错误（id 和 name 字段）

输入
```
2021-12-22 21:18:57 ( _ ?(123456789)
消息内容

2021-12-22 21:20:41 ( * ?(123456789)
消息内容

2020-03-15 21:21:45 (o´・ω・`)σ<mail@someaddress.com>
消息内容
```

输出
```json
[
  {
    "date": "2021-12-22 21:18:57",
    "id": " _ ?(123456789",
    "name": "",
    "content": "消息内容"
  },
  {
    "date": "2021-12-22 21:20:41",
    "id": " * ?(123456789",
    "name": "",
    "content": "消息内容"
  },
  {
    "date": "2020-03-15 21:21:45",
    "id": "o´・ω・`",
    "name": "(o´・ω・`)σ<mail@someaddr",
    "content": "消息内容"
  }
]
```

希望可以得到修复，让这个项目更健壮！

**Comment by hikariyo** [comment]
fixed in 53b4135
